Various improvements and fixes
cpanato/mattermost-plugin-alertmanager pull request #75
Opened 2022-11-22 10:30 UTC by hanzei

Please take a look a the individual commits.

Follow up on https://github.com/mattermost/mattermost-plugin-alertmanager/pull/1#pullrequestreview-1189661936

2022-11-22 10:33 UTC, hanzei commented
cc @javaguirre

2022-11-22 11:03 UTC, javaguirre approved these changes
Thank you Ben! LGTM!

2022-12-09 08:28 UTC, cpanato requested changes
lgtm
just a few nits

2022-12-09 08:28 UTC, cpanato commented on server/alertmanager/retry.go
> +				return errors.Errorf("status code is %d not 200", resp.StatusCode)
github.com/pkg/errors is deprecated, please keep using `fmt.errorf`

2022-12-09 08:28 UTC, cpanato commented on server/alertmanager/retry.go
> +				return errors.Errorf("status code is %d not 3xx", resp.StatusCode)
same here

2022-12-09 08:28 UTC, cpanato commented on server/alertmanager/silences.go
> +		return errors.Errorf("silence ID cannot be empty")
github.com/pkg/errors is deprecated, please keep using `fmt.errorf`

2022-12-09 08:28 UTC, cpanato commented on server/alertmanager/silences.go
> +		return errors.Errorf(string(body))
github.com/pkg/errors is deprecated, please keep using `fmt.errorf`

2022-12-09 08:28 UTC, cpanato commented on server/configuration.go
> +		return errors.New("must set a Team")
since you are adding new things, please move the `"github.com/pkg/errors"` to `errors`

2022-12-09 14:14 UTC, cpanato approved these changes
thank you

2022-12-09 14:21 UTC, merged